using GymBackend.Data;
using GymBackend.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

var jwtKey = builder.Configuration["Jwt:Key"];

if (string.IsNullOrWhiteSpace(jwtKey) || jwtKey.Length < 32)
{
    throw new InvalidOperationException("Jwt:Key debe tener al menos 32 caracteres.");
}

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
            ValidateIssuer = false,
            ValidateAudience = false,
            ValidateLifetime = true,
            ClockSkew = TimeSpan.FromMinutes(1),
        };
    });

builder.Services.AddAuthorization();

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.WithOrigins("http://localhost:4200")
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("AllowFrontend");

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

    var maxRetries = 10;
    var retryDelay = TimeSpan.FromSeconds(3);

    for (int i = 1; i <= maxRetries; i++)
    {
        try
        {
            db.Database.EnsureCreated();

            db.Database.ExecuteSqlRaw(
                "ALTER TABLE \"Users\" ADD COLUMN IF NOT EXISTS \"Username\" text NOT NULL DEFAULT '';" );

            db.Database.ExecuteSqlRaw(
                "ALTER TABLE \"Users\" ADD COLUMN IF NOT EXISTS \"Enabled\" boolean NOT NULL DEFAULT true;" );

            db.Database.ExecuteSqlRaw(
                "CREATE TABLE IF NOT EXISTS \"ScheduleSlots\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Day\" text NOT NULL, \"StartTime\" text NOT NULL, \"EndTime\" text NOT NULL, \"Zone\" text NOT NULL, \"Capacity\" integer NOT NULL, \"Enabled\" boolean NOT NULL);" );

            db.Database.ExecuteSqlRaw(
                "CREATE TABLE IF NOT EXISTS \"Attendances\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"UserId\" integer NOT NULL, \"Rut\" text NOT NULL, \"UserName\" text NOT NULL, \"Date\" text NOT NULL, \"EntryTime\" timestamptz NULL, \"EntryAdminRut\" text NULL, \"ExitTime\" timestamptz NULL, \"ExitAdminRut\" text NULL, \"ReservationId\" integer NULL);" );

            db.Database.ExecuteSqlRaw(
                "ALTER TABLE \"Attendances\" ADD COLUMN IF NOT EXISTS \"CheckedIn\" boolean NOT NULL DEFAULT false;" );

            var admin = await db.Users
                .Where(user => user.Role == "Admin" && user.Username == string.Empty)
                .OrderBy(user => user.Id)
                .FirstOrDefaultAsync();

            if (admin is not null)
            {
                admin.Username = admin.Email.Split('@')[0];
                await db.SaveChangesAsync();
            }

            if (!await db.ScheduleSlots.AnyAsync())
            {
                var days = new[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" };
                var ranges = new[]
                {
                    (Start: "08:00", End: "09:30"),
                    (Start: "09:30", End: "11:00"),
                    (Start: "11:00", End: "12:30"),
                    (Start: "13:00", End: "14:30"),
                };

                db.ScheduleSlots.AddRange(
                    days.SelectMany(day => ranges.Select(range => new ScheduleSlot
                    {
                        Day = day,
                        StartTime = range.Start,
                        EndTime = range.End,
                        Zone = "Sala de Pesas",
                        Capacity = 20,
                        Enabled = true,
                    })));

                await db.SaveChangesAsync();
            }

            Console.WriteLine("Base de datos inicializada correctamente.");
            break;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Intento {i}/{maxRetries}: no se pudo conectar a la base de datos.");
            Console.WriteLine(ex.Message);

            if (i == maxRetries)
            {
                throw;
            }

            Thread.Sleep(retryDelay);
        }
    }
}

app.Run();
